name: Backfill Polarity Scores

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at 8:00pm ET
  workflow_dispatch:

permissions:
  contents: read
  actions: read  # manual trigger

jobs:
  backfill-emerging:
    name: Backfill Emerging Risk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install newspaper4k vaderSentiment pandas nltk lxml-html-clean

      - name: Run emerging backfill script
        run: |
          python scripts/backfill_emerging.py
        continue-on-error: false

      - name: Save emerging logs manually
        if: always()
        run: cp online_sentiment/output/emerging_risks_online_sentiment.csv ${{ github.workspace }}/emerging.csv
        # technical debt! Replace with upload-artifact once GitHub fixes missing download info

      - name: Emerging data failure notif
        if: failure()
        run: echo "Backfilling Emerging dataset failed. See logs."

  backfill-enterprise:
    name: Backfill Enterprise Risk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install newspaper4k vaderSentiment pandas nltk lxml-html-clean

      - name: Run enterprise backfill script
        run: |
          python scripts/backfill_enterprise.py
        continue-on-error: false

      - name: Save enterprise logs manually
        if: always()
        run: cp online_sentiment/output/enterprise_risks_online_sentiment.csv ${{ github.workspace }}/enterprise.csv
        # technical debt! Replace with upload-artifact once GitHub fixes missing download info

      - name: Enterprise data failure notif
        if: failure()
        run: echo "Backfilling Emerging dataset failed. See logs."
