name: Daily Data Update with Refresh Log

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Which job to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - enterprise
          - emerging

jobs:
  update-enterprise-risk:
    runs-on: ubuntu-latest
    outputs:
      enterprise_path: ${{ steps.enterprise_output.outputs.file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml[html_clean]

      - name: Run Enterprise Risk News script
        run: python EnterpriseRiskNews.py

      - name: Save Enterprise CSV Path
        id: enterprise_output
        run: echo "file=output/enterprise_risks_online_sentiment.csv" >> $GITHUB_OUTPUT

  update-emerging-risk:
    runs-on: ubuntu-latest
    outputs:
      emerging_path: ${{ steps.emerging_output.outputs.file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml[html_clean]

      - name: Run Emerging Risk News script
        run: python EmergingRiskNews.py

      - name: Save Emerging CSV Path
        id: emerging_output
        run: echo "file=output/emerging_risks_online_sentiment.csv" >> $GITHUB_OUTPUT

  commit-csvs:
    runs-on: ubuntu-latest
    needs: [update-enterprise-risk, update-emerging-risk]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Commit CSVs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git pull
          git add output/*.csv
          git commit -m "Update Enterprise and Emerging Risk CSVs" || echo "No changes to commit"
          git push
