name: Daily Data Update with Refresh Log

on:
  schedule:
    - cron: '0 7 * * *'  # 3AM ET
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Which job to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - enterprise
          - emerging

jobs:
  update-enterprise-risk:
    if: github.event_name == 'schedule' || github.event.inputs.run_job == 'all' || github.event.inputs.run_job == 'enterprise'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml[html_clean]

      - run: mkdir -p online_sentiment/output

      - name: Run Enterprise Risk News script
        run: python EnterpriseRiskNews.py

  update-emerging-risk:
    if: github.event_name == 'schedule' || github.event.inputs.run_job == 'all' || github.event.inputs.run_job == 'emerging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml[html_clean]

      - run: mkdir -p online_sentiment/output

      - name: Run Emerging Risk News script
        run: python EmergingRiskNews.py

      - name: Upload CSV output
        uses: actions/upload-artifact@v4
        with:
          name: emerging-risks-sentiment
          path: online_sentiment/output/emerging_risks_online_sentiment.csv
