name: Daily Data Update with Refresh Log

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Which job to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - enterprise
          - emerging

jobs:
  update-enterprise-risk:
    if: github.event_name == 'schedule' || github.event.inputs.run_job == 'all' || github.event.inputs.run_job == 'enterprise'
    runs-on: ubuntu-latest
    steps:
      - name: Hello from Enterprise
        run: echo "Enterprise job ran!"

  update-emerging-risk:
    needs: update-enterprise-risk
    if: github.event_name == 'schedule' || github.event.inputs.run_job == 'all' || github.event.inputs.run_job == 'emerging'
    runs-on: ubuntu-latest
    steps:
      - name: Hello from Emerging
        run: echo "Emerging job ran!"
