name: Daily Data Update with Refresh Log

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 3am
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Which job to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - enterprise
          - emerging

jobs:
  process-enterprise:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_job == 'all' || github.event.inputs.run_job == 'enterprise' || github.event.inputs.run_job == '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml[html_clean] newspaper3k vaderSentiment googlenewsdecoder

      - name: Run Enterprise Risk News script
        run: python EnterpriseRiskNews.py

      - name: Check CSV size
        run: |
          file=output/enterprise_risks_online_sentiment.csv
          if [ -f "$file" ]; then
            size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file")
            if [ $size -gt 50000000 ]; then
              echo "Error: $file exceeds 50MB ($size bytes)"
              exit 1
            fi
            echo "Enterprise CSV size: $size bytes"
          else
            echo "No enterprise CSV found"
          fi

      - name: Compress enterprise CSV
        run: |
          file=output/enterprise_risks_online_sentiment.csv
          if [ -f "$file" ]; then
            gzip "$file"
          else
            echo "No enterprise CSV to compress"
          fi

      - name: Upload enterprise artifact
        uses: actions/upload-artifact@v3
        with:
          name: enterprise-data
          path: output/enterprise_risks_online_sentiment.csv.gz

  process-emerging:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run_job == 'all' || github.event.inputs.run_job == 'emerging' || github.event.inputs.run_job == '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml[html_clean] newspaper3k vaderSentiment googlenewsdecoder

      - name: Run Emerging Risk News script
        run: python EmergingRiskNews.py

      - name: Check CSV size
        run: |
          file=output/emerging_risks_online_sentiment.csv
          if [ -f "$file" ]; then
            size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file")
            if [ $size -gt 50000000 ]; then
              echo "Error: $file exceeds 50MB ($size bytes)"
              exit 1
            fi
            echo "Emerging CSV size: $size bytes"
          else
            echo "No emerging CSV found"
          fi

      - name: Compress emerging CSV
        run: |
          file=output/emerging_risks_online_sentiment.csv
          if [ -f "$file" ]; then
            gzip "$file"
          else
            echo "No emerging CSV to compress"
          fi

      - name: Upload emerging artifact
        uses: actions/upload-artifact@v3
        with:
          name: emerging-data
          path: output/emerging_risks_online_sentiment.csv.gz

  publish-data:
    needs: [process-enterprise, process-emerging]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: data

      - name: Download enterprise artifact
        if: ${{ github.event.inputs.run_job == 'all' || github.event.inputs.run_job == 'enterprise' || github.event.inputs.run_job == '' }}
        uses: actions/download-artifact@v3
        with:
          name: enterprise-data
          path: output/

      - name: Download emerging artifact
        if: ${{ github.event.inputs.run_job == 'all' || github.event.inputs.run_job == 'emerging' || github.event.inputs.run_job == '' }}
        uses: actions/download-artifact@v3
        with:
          name: emerging-data
          path: output/

      - name: Decompress CSVs
        run: |
          for file in output/*.csv.gz; do
            if [ -f "$file" ]; then
              gunzip -c "$file" > "${file%.gz}"
            else
              echo "No CSVs to decompress"
            fi
          done

      - name: Commit and push CSVs to data branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git checkout -b data || git checkout data
          mkdir -p output
          mv output/*.csv output/ 2>/dev/null || echo "No CSVs to move"
          git add output/*.csv
          if git diff --cached --quiet; then
            echo "No changes detected in the CSV files"
          else
            echo "Changes detected, committing..."
            git commit -m "Update Enterprise and Emerging Risk CSVs - $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin data --force
          fi

      - name: Debug final state
        run: |
          echo "****FINAL STATE DEBUG ******"
          echo "output directory contains:"
          ls -la output/
          for file in output/*.csv; do
            if [ -f "$file" ]; then
              size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file")
              echo "File: $file, Size: $size bytes"
            fi
          done
          echo "*******************************"
