name: Run Python Script and Save CSV

on:
  # Schedule the workflow to run every Monday at 6:00 AM Eastern Time (ET)
  schedule:
    - cron: '0 10 * * 1' # 10:00 UTC is 6:00 AM ET (adjust for daylight savings)
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install -r requirements.txt

    - name: Install lxml and lxml_html_clean
      run: |
        pip install lxml[html_clean] lxml_html_clean

    - name: Create Output Directory
      run: mkdir -p online_sentiment/output

    - name: Run Enterprise Risk News script
      run: |
        python EnterpriseRiskNews.py

    - name: Run Emerging Risk News script
      run: |
        python EmergingRiskNews.py

    - name: Check for Changes
      id: check_changes
      run: |
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit."
          echo "has_changes=false" >> $GITHUB_ENV
        else
          echo "Changes detected."
          echo "has_changes=true" >> $GITHUB_ENV
        fi

    - name: Push generated CSV files
      if: env.has_changes == 'true'
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add online_sentiment/output/*.csv
        git commit -m "Update CSV files"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
